/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.menu;

import controladores.usuarios.UsuariosDAO;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelos.clases.usuarios.Usuario;
import vistas.secciones.Catalogos.Catalogo;
import vistas.secciones.Citas;
import vistas.secciones.Colecciones;
import vistas.secciones.Sedes;
import vistas.secciones.SobreNosotros;
import vistas.secciones.perfil.LoginCliente;

/**
 *
 * @author HOME
 */
public class MenuUsuario extends javax.swing.JFrame {

    Usuario usuarioLogueado = Usuario.getUsuarioActual();
    UsuariosDAO usuarioDAO = new UsuariosDAO();
    
    public MenuUsuario() {
        initComponents();

        if (Usuario.isLoggedIn()) {
            txtStatus.setText("Activo");
            txtNombre.setText(usuarioLogueado.getNombre_completo().toUpperCase());
        } else {
            txtStatus.setText("Desconectado");
            txtNombre.setText("Invitado");
        }

        try {
            URL imagenURL1 = new URL("https://raw.githubusercontent.com/iJosueeh/imagenes-poo-proyecto/refs/heads/main/Collectibles.png");
            ImageIcon iconColecciones = new ImageIcon(imagenURL1);
            btnColecciones.setIcon(iconColecciones);
            
            URL imagenURL2 = new URL("https://raw.githubusercontent.com/iJosueeh/imagenes-poo-proyecto/refs/heads/main/Delivery.png");
            ImageIcon iconSedes = new ImageIcon(imagenURL2);
            btnSedes.setIcon(iconSedes);
            
            URL imagenURL3 = new URL("https://raw.githubusercontent.com/iJosueeh/imagenes-poo-proyecto/refs/heads/main/Info%20Squared.png");
            ImageIcon iconSobreNosotros = new ImageIcon(imagenURL3);
            btnSobreNosotros.setIcon(iconSobreNosotros);
            
            URL imagenURL4 = new URL("https://raw.githubusercontent.com/iJosueeh/imagenes-poo-proyecto/refs/heads/main/Quote.png");
            ImageIcon iconCitas = new ImageIcon(imagenURL4);
            btnCitas.setIcon(iconCitas);
            
            URL imagenURL5 = new URL("https://raw.githubusercontent.com/iJosueeh/imagenes-poo-proyecto/refs/heads/main/User.png");
            ImageIcon iconUser = new ImageIcon(imagenURL5);
            btnIniciarSesion.setIcon(iconUser);
            
            URL imagenURL6 = new URL("https://raw.githubusercontent.com/iJosueeh/imagenes-poo-proyecto/refs/heads/main/Go_Back.png");
            ImageIcon iconExit = new ImageIcon(imagenURL6);
            btnAbandonar.setIcon(iconExit);
            
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnColecciones = new javax.swing.JButton();
        btnSedes = new javax.swing.JButton();
        btnSobreNosotros = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        btnAbandonar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(118, 98, 78));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 680));

        btnColecciones.setBackground(new java.awt.Color(204, 204, 204));
        btnColecciones.setFont(new java.awt.Font("Readex Pro Medium", 0, 12)); // NOI18N
        btnColecciones.setText("Colecciones");
        btnColecciones.setBorder(null);
        btnColecciones.setMaximumSize(new java.awt.Dimension(141, 18));
        btnColecciones.setMinimumSize(new java.awt.Dimension(141, 18));
        btnColecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColeccionesActionPerformed(evt);
            }
        });

        btnSedes.setBackground(new java.awt.Color(204, 204, 204));
        btnSedes.setFont(new java.awt.Font("Readex Pro Medium", 0, 12)); // NOI18N
        btnSedes.setText("Sedes");
        btnSedes.setBorder(null);
        btnSedes.setMaximumSize(new java.awt.Dimension(141, 18));
        btnSedes.setMinimumSize(new java.awt.Dimension(141, 18));
        btnSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSedesActionPerformed(evt);
            }
        });

        btnSobreNosotros.setBackground(new java.awt.Color(204, 204, 204));
        btnSobreNosotros.setFont(new java.awt.Font("Readex Pro Medium", 0, 12)); // NOI18N
        btnSobreNosotros.setText("Sobre Nosotros");
        btnSobreNosotros.setBorder(null);
        btnSobreNosotros.setMaximumSize(new java.awt.Dimension(141, 18));
        btnSobreNosotros.setMinimumSize(new java.awt.Dimension(141, 18));
        btnSobreNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreNosotrosActionPerformed(evt);
            }
        });

        btnCitas.setBackground(new java.awt.Color(204, 204, 204));
        btnCitas.setFont(new java.awt.Font("Readex Pro Medium", 0, 12)); // NOI18N
        btnCitas.setText("Citas");
        btnCitas.setBorder(null);
        btnCitas.setMaximumSize(new java.awt.Dimension(141, 18));
        btnCitas.setMinimumSize(new java.awt.Dimension(141, 18));
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        btnAbandonar.setBackground(new java.awt.Color(255, 149, 0));
        btnAbandonar.setFont(new java.awt.Font("Readex Pro Medium", 0, 12)); // NOI18N
        btnAbandonar.setText("Abandonar");
        btnAbandonar.setBorder(null);
        btnAbandonar.setMaximumSize(new java.awt.Dimension(141, 18));
        btnAbandonar.setMinimumSize(new java.awt.Dimension(141, 18));
        btnAbandonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarActionPerformed(evt);
            }
        });

        btnIniciarSesion.setBackground(new java.awt.Color(255, 149, 0));
        btnIniciarSesion.setFont(new java.awt.Font("Readex Pro Medium", 0, 12)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.setMaximumSize(new java.awt.Dimension(141, 18));
        btnIniciarSesion.setMinimumSize(new java.awt.Dimension(141, 18));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 229, 183));
        jLabel1.setText("Estado Actual: ");

        txtStatus.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtStatus.setText("Desconectado");

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(229, 229, 183));
        jLabel4.setText("Nombre Completo: ");

        txtNombre.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("Invitado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatus))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addComponent(btnColecciones, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(btnSedes, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(btnSobreNosotros, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(btnCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(btnAbandonar, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(btnColecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSedes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSobreNosotros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbandonar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnPanel.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator2.setBackground(new java.awt.Color(255, 138, 138));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Readex Pro Light", 0, 18)); // NOI18N
        jLabel2.setText("El brillo que hace latir tu corazón");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setText("Radiant Legacy");

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(265, 265, 265))
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel2))
                    .addGroup(btnPanelLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jPanel1.add(btnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 760, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbandonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarActionPerformed
        String mensaje = "¿Seguro que quieres salir?\nTendrás que iniciar sesión nuevamente para seguir comprando.";

        int seleccion = JOptionPane.showOptionDialog(
                this,
                mensaje,
                "Confirmar cierre del programa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                new Object[]{"Sí", "No"}, // Opciones mostradas al usuario
                "No" // Opción predeterminada seleccionada
        );

        if (seleccion == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Gracias por utilizar el programa, ¡vuelve pronto!");
            Usuario.setLoggedIn(false);

            if (usuarioLogueado != null) {
                usuarioDAO.actualizarEstadoInactivo(usuarioLogueado.getIdUsuario());
            }
            
            MenuInicial menuInicial = new MenuInicial();
            menuInicial.setVisible(true);
            menuInicial.setLocationRelativeTo(null);
            this.dispose();
        }

    }//GEN-LAST:event_btnAbandonarActionPerformed

    private void btnSobreNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreNosotrosActionPerformed
        SobreNosotros sobreNosotros = new SobreNosotros();
        sobreNosotros.setVisible(true);
        sobreNosotros.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnSobreNosotrosActionPerformed

    private void btnSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSedesActionPerformed
        Sedes sedeLocales = new Sedes();
        sedeLocales.setVisible(true);
        sedeLocales.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnSedesActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        Citas citas = new Citas();
        citas.setVisible(true);
        citas.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btnColeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColeccionesActionPerformed
        Colecciones colecciones = new Colecciones();
        colecciones.setVisible(true);
        colecciones.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_btnColeccionesActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

        if (Usuario.isLoggedIn()) {
            JOptionPane.showMessageDialog(null, "Ya tienes una sesión activa.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            LoginCliente loginCliente = new LoginCliente();
            loginCliente.setVisible(true);
            loginCliente.setLocationRelativeTo(null);

            this.dispose();
        }

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonar;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnColecciones;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSedes;
    private javax.swing.JButton btnSobreNosotros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
